language: node_js
node_js:
  - "12.2.0"
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "dimosellaatwork-github"

cache:
  directories:
  - node_modules
  - '$HOME/.sonar/cache'

install:
  - npm install

script:
  - npm run lint
  - npm test
  - sonar-scanner
